grid_size = 100
cell_size = 1 / grid_size
base_cell_weight = 1
max_cell_weight = 7
population_size = 100
generations = 200
tournament_size = 5
mutation_probability = 0.2
optimization_interval = 7
no_improvement_termination = 30